#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Hubs,  S2, HTServo,  none,     none,     none)
#pragma config(Motor,  mtr_S1_C1_1,     motorLeft,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorRight,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     motorArmRotation, tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorG,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S2_C1_1,    servoArmPitch,        tServoStandard)
#pragma config(Servo,  srvo_S2_C1_2,    servoArmGrip,         tServoContinuousRotation)
#pragma config(Servo,  srvo_S2_C1_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// The Doppler Effect
// 2013-14 Autonomous Program
// Body File

// File: "Autonomous.c"
// Created: 10/24/2013
// Modified: 10/24/2013

#include "Autonomous.h"

task main() {
}

void driveForTime(int power, int time) {
	driveForTime(power, time, DEFAULT_DRIVE_SMOOTHEN);
}

void driveForTime(int power, int time, bool smoothen) {
	motor[motorLeft] = 0;
	motor[motorRight] = 0;

	if (smoothen) {
		float timef = (float) time;
		float powerf = (float) power;
		float newPower;

		for (float i = 0.0; i < timef; i += 10) {
			newPower = powerf*sinDegrees((i/timef)*180.0);

			motor[motorLeft] = newPower;
			motor[motorRight] = newPower;

			wait10Msec(1);
		}
	} else {
		motor[motorLeft] = power;
		motor[motorRight] = power;

		wait1Msec(time);
	}

	motor[motorLeft] = 0;
	motor[motorRight] = 0;
}
