
// The Doppler Effect 2013
// Autonomous 1 - Header

#define SENSOR_SONAR_4_THRESHOLD 10

#define ROTATION_CW_MOTOR_POWER_LEFT 75
#define ROTATION_CW_MOTOR_POWER_RIGHT -75

#define ROTATION_CCW_MOTOR_POWER_LEFT -75
#define ROTATION_CCW_MOTOR_POWER_RIGHT 75

#define DRIVE_FORWARD_MOTOR_POWER_LEFT 75
#define DRIVE_FORWARD_MOTOR_POWER_RIGHT 75

#define ENCODER_TARGET_A_1_LEFT 100
#define ENCODER_TARGET_A_1_RIGHT 100

#define ENCODER_TARGET_A_2_LEFT 500
#define ENCODER_TARGET_A_2_RIGHT 500

#define ENCODER_TARGET_A_3_LEFT 100
#define ENCODER_TARGET_A_3_RIGHT 100

#define WAIT_A_1_2 150
#define WAIT_A_2_3 150
#define WAIT_A_3_4 150
#define WAIT_A_4 150
