#pragma config(Hubs,  S3, HTServo,  none,     none,     none)
#pragma config(Hubs,  S4, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S1,     sonar,          sensorSONAR)
#pragma config(Motor,  mtr_S4_C1_1,     motorRight,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S4_C1_2,     motorLeft,     tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S4_C2_1,     motorF,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S4_C2_2,     motorG,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S3_C1_1,    servoArm,             tServoStandard)
#pragma config(Servo,  srvo_S3_C1_2,    servoGripper,         tServoStandard)
#pragma config(Servo,  srvo_S3_C1_3,    servoArmRotation,     tServoContinuousRotation)
#pragma config(Servo,  srvo_S3_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S3_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S3_C1_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// The Doppler Effect 2013
// Autonomous

#include "Autonomous.h"

void initialize() {
}

void startA() {
	nMotorEncoder[motorLeft]  = 0;
	nMotorEncoder[motorRight] = 0;

	nMotorEncoderTarget[motorLeft]  = ENCODER_TARGET_A_1_LEFT;
	nMotorEncoderTarget[motorRight] = ENCODER_TARGET_A_1_RIGHT;

	motor[motorLeft]  = ROTATION_CW_MOTOR_POWER_LEFT;
	motor[motorRight] = ROTATION_CW_MOTOR_POWER_RIGHT;

	while (nMotorRunState[motorLeft] != runStateIdle) {
		wait1Msec(50);
	}

	motor[motorLeft]  = 0;
	motor[motorRight] = 0;

	wait1Msec(WAIT_A_1_2);

	nMotorEncoder[motorLeft]  = 0;
	nMotorEncoder[motorRight] = 0;

	nMotorEncoderTarget[motorLeft]  = ENCODER_TARGET_A_2_LEFT;
	nMotorEncoderTarget[motorRight] = ENCODER_TARGET_A_2_RIGHT;

	motor[motorLeft]  = DRIVE_FORWARD_MOTOR_POWER_LEFT;
	motor[motorRight] = DRIVE_FORWARD_MOTOR_POWER_RIGHT;

	while (nMotorRunState[motorLeft] != runStateIdle) {
		wait1Msec(50);
	}

	motor[motorLeft]  = 0;
	motor[motorRight] = 0;

	wait1Msec(WAIT_A_2_3);

	nMotorEncoder[motorLeft]  = 0;
	nMotorEncoder[motorRight] = 0;

	nMotorEncoderTarget[motorLeft]  = ENCODER_TARGET_A_3_LEFT;
	nMotorEncoderTarget[motorRight] = ENCODER_TARGET_A_3_RIGHT;

	motor[motorLeft]  = ROTATION_CCW_MOTOR_POWER_LEFT;
	motor[motorRight] = ROTATION_CCW_MOTOR_POWER_RIGHT;

	while (nMotorRunState[motorLeft] != runStateIdle) {
		wait1Msec(50);
	}

	motor[motorLeft]  = 0;
	motor[motorRight] = 0;

	wait1Msec(WAIT_A_3_4);

	motor[motorLeft]  = DRIVE_FORWARD_MOTOR_POWER_LEFT;
	motor[motorRight] = DRIVE_FORWARD_MOTOR_POWER_RIGHT;

	while (SensorValue[sonar] > SENSOR_SONAR_4_THRESHOLD) {}

	motor[motorLeft]  = 0;
	motor[motorRight] = 0;

	wait1Msec(WAIT_A_4);
}

void startB() {

}

task main() {

}
